apiVersion: apps/v1
kind: Deployment
metadata:
  name: btry-indi-deployment
spec:
  replicas: 6  # Number of desired replicas
  selector:
    matchLabels:
      app: btry-indi
  template:
    metadata:
      labels:
        app: btry-indi
    spec:
      containers:
      - name: btry-indi
        image: yash5090/btry-indi:latest
        ports:
        - containerPort: 5000
